# Generated by Django 2.2.16 on 2022-03-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHostFileRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(verbose_name='业务ID')),
                ('job_instance_id', models.BigIntegerField(verbose_name='作业实例ID')),
                ('bk_host_innerip', models.CharField(max_length=128, verbose_name='主机IP')),
                ('backup_directory', models.CharField(max_length=256, verbose_name='文件目录')),
                ('file_suffix', models.CharField(max_length=32, verbose_name='文件后缀')),
                ('backup_file_name', models.CharField(max_length=256, verbose_name='备份文件名')),
                ('backup_time', models.DateTimeField(auto_now_add=True, verbose_name='备份时间')),
                ('backup_operator', models.CharField(max_length=256, verbose_name='备份人')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('bk_biz_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='业务ID')),
                ('bk_biz_name', models.CharField(max_length=128, verbose_name='业务名称')),
            ],
            options={
                'verbose_name': '业务信息表',
                'verbose_name_plural': '业务信息表',
                'db_table': 'config_query_business',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('bk_host_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='主机ID')),
                ('bk_host_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='主机名称')),
                ('bk_host_innerip', models.CharField(blank=True, max_length=128, null=True, verbose_name='内网IP')),
                ('bk_host_outerip', models.CharField(blank=True, max_length=128, null=True, verbose_name='外网IP')),
                ('operator', models.TextField(blank=True, null=True, verbose_name='负责人')),
                ('bk_bak_operator', models.TextField(blank=True, null=True, verbose_name='备份负责人')),
                ('bk_cloud_id', models.IntegerField(blank=True, null=True, verbose_name='云区域')),
                ('bk_biz_id', models.CharField(default='', max_length=128, verbose_name='所属业务ID')),
                ('bk_set_id', models.CharField(default='', max_length=128, verbose_name='所属集群ID')),
                ('bk_module_id', models.CharField(default='', max_length=128, verbose_name='所属模块ID')),
            ],
            options={
                'verbose_name': '主机信息表',
                'verbose_name_plural': '主机信息表',
                'db_table': 'config_query_host',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('bk_module_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='模块ID')),
                ('bk_module_name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('bk_set_id', models.IntegerField(blank=True, null=True, verbose_name='所属集群ID')),
                ('bk_biz_id', models.IntegerField(verbose_name='所属业务ID')),
            ],
            options={
                'verbose_name': '模块信息表',
                'verbose_name_plural': '模块信息表',
                'db_table': 'config_query_module',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('bk_set_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='集群ID')),
                ('bk_set_name', models.CharField(max_length=128, verbose_name='集群名称')),
                ('bk_biz_id', models.IntegerField(verbose_name='所属业务ID')),
            ],
            options={
                'verbose_name': '集群信息表',
                'verbose_name_plural': '集群信息表',
                'db_table': 'config_query_set',
            },
        ),
    ]
