# Generated by Django 2.2.16 on 2022-03-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='bk_cloud_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='云区域名称'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_system',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='操作系统类型'),
        ),
    ]
